"""empty message

Revision ID: e6549ebc183f
Revises: 3b8817bfdc38
Create Date: 2019-11-25 14:04:45.552451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6549ebc183f'
down_revision = '3b8817bfdc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('time', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'time')
    op.drop_column('events', 'active')
    # ### end Alembic commands ###
